Initial Refactor including buildParameters and initializeContext
cqframework/vscode-cql pull request #46
Opened 2024-07-30 17:44 UTC by jreyno77

![image](https://github.com/user-attachments/assets/f1b92c7f-5eee-4b17-9294-15039a3318d9)

- executeCQL has been refactored to only run the Execute CQL Command and output text to the results file.
- buildParameters has only replaced executeCqlFile and builds the operationArgs required for execution as of right now there is no connection manager use.
- initializeState has been stubbed out and simply checks if a cql file is the execution state (simple right now) and runs buildParameters, then executeCql.

-- Additional Notes --
*All args being passed to the Execute Cql Command are the same.*
*Execution output is the same, but test path and test names have swapped places.*

2024-07-30 23:01 UTC, holly-smile requested changes
Couple little things but looks just about good to me!

2024-07-31 15:27 UTC, jreyno77 commented on .vscode/launch.json
> +      "args": ["--extensionDevelopmentPath=${workspaceFolder}"],
I did not mean to include this sorry about that

2024-07-31 15:33 UTC, jreyno77 commented on src/executeCql.ts
> +export async function executeCQL(evaluationParameters: EvaluationParameters) {
Should I remove the type EvaluationParameters? If it's not making things more readable, then I wonder if it is necessary.

2024-07-31 15:51 UTC, jreyno77 commented on .vscode/launch.json
> +      "args": ["--extensionDevelopmentPath=${workspaceFolder}"],
Added that back in.

2024-07-31 15:57 UTC, jreyno77 commented on src/initializeState.ts
> +export async function initializeState(uri: Uri) {
I like normalizeCqlExecution. I understand why initializeState feels so bad. I think normalizing Cql Execution specifies the true purpose here, and I think it is execution-specific.

2024-07-31 17:26 UTC, holly-smile commented on src/initializeState.ts
> +export async function initializeState(uri: Uri) {
That sounds good to me!

2024-07-31 17:29 UTC, holly-smile approved these changes
LGTM!

2024-07-31 17:49 UTC, merged